// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO7w_pmLRkBC1OI-qlhPpbEpOhAcBpjwM',
    appId: '1:402879378420:web:b788d942856d2353fcbfa1',
    messagingSenderId: '402879378420',
    projectId: 'social-media-app-00',
    authDomain: 'social-media-app-00.firebaseapp.com',
    storageBucket: 'social-media-app-00.firebasestorage.app',
    measurementId: 'G-NKRL89G6DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZ7WV12s1pgOfmxkA8rM8XEelTDp7Heg',
    appId: '1:402879378420:android:51d0d8b2b2c26cf1fcbfa1',
    messagingSenderId: '402879378420',
    projectId: 'social-media-app-00',
    storageBucket: 'social-media-app-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8e80cLMshg4PDClqDdEbvzXLxR5jAsYU',
    appId: '1:402879378420:ios:d061b18c8e6e762dfcbfa1',
    messagingSenderId: '402879378420',
    projectId: 'social-media-app-00',
    storageBucket: 'social-media-app-00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8e80cLMshg4PDClqDdEbvzXLxR5jAsYU',
    appId: '1:402879378420:ios:d061b18c8e6e762dfcbfa1',
    messagingSenderId: '402879378420',
    projectId: 'social-media-app-00',
    storageBucket: 'social-media-app-00.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO7w_pmLRkBC1OI-qlhPpbEpOhAcBpjwM',
    appId: '1:402879378420:web:dae1a4a3921e692dfcbfa1',
    messagingSenderId: '402879378420',
    projectId: 'social-media-app-00',
    authDomain: 'social-media-app-00.firebaseapp.com',
    storageBucket: 'social-media-app-00.firebasestorage.app',
    measurementId: 'G-0W7NM83S55',
  );
}
